version: "3.8"
services:
  postgres:
    image: postgres:14.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgpw
      - POSTGRES_DB=api
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d api"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 5s
  localstack:
    image: localstack/localstack:0.14.1
    restart: always
    environment:
      - SERVICES=s3
      - DATADIR=/tmp/localstack/data
    ports:
      - '4566:4566'
    volumes:
      - ./aws:/docker-entrypoint-initaws.d
      - s3-data:/tmp/localstack
volumes:
  db-data:
  s3-data:
